sudo: require
language: cpp
compiler: clang
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - llvm-3.8-dev
            - clang-3.8
            - libc++-dev
            - clang-format
            - ninja-build

install:
    - wget -O /tmp/antlr4.zip https://www.antlr.org/download/antlr4-cpp-runtime-4.7.2-source.zip
    - wget -O /tmp/antlr4.jar https://www.antlr.org/download/antlr-4.7.2-complete.jar
    - sudo cp /tmp/antlr4.jar /usr/local/bin/antlr4.jar
    - cd /tmp
    - unzip /tmp/antlr4.zip -d antlr4-cpp-runtime
    - cd antlr4-cpp-runtime
    - mkdir build && mkdir run && cd build
    - cmake ..
    - make
    - sudo make install

script:
    - cd $TRAVIS_BUILD_DIR
    - clang -v && make --version && cmake --version
    - ./check_clang_format.sh
    - ./build.sh
